--
-- Supabase Schema Export
-- Generated by Antigravity
--

-- Enable Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Tables

CREATE TABLE public.libraries (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    owner_id uuid REFERENCES auth.users(id),
    name text NOT NULL,
    address text NOT NULL,
    city text NOT NULL,
    state text NOT NULL,
    pincode char(6) NOT NULL,
    phone text NOT NULL CHECK (phone ~ '^[6-9]\d{9}$'),
    is_gender_neutral boolean DEFAULT false,
    male_seats integer DEFAULT 0,
    female_seats integer DEFAULT 0,
    neutral_seats integer DEFAULT 0,
    has_lockers boolean DEFAULT false,
    male_lockers integer DEFAULT 0,
    female_lockers integer DEFAULT 0,
    neutral_lockers integer DEFAULT 0,
    subscription_plan text CHECK (subscription_plan = ANY (ARRAY['1m'::text, '3m'::text, '6m'::text, '12m'::text])),
    subscription_status text DEFAULT 'inactive'::text CHECK (subscription_status = ANY (ARRAY['active'::text, 'inactive'::text, 'expired'::text, 'deleted'::text])),
    subscription_start timestamptz,
    subscription_end timestamptz,
    delete_date timestamptz,
    data_cleared boolean DEFAULT false,
    original_plan_price numeric,
    onboarding_done boolean DEFAULT false,
    notif_sent_7d boolean DEFAULT false,
    notif_sent_3d boolean DEFAULT false,
    notif_sent_1d boolean DEFAULT false,
    cleanup_warn_sent boolean DEFAULT false,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.temp_registrations (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    razorpay_order_id text UNIQUE NOT NULL,
    form_data jsonb NOT NULL,
    created_at timestamptz DEFAULT now(),
    expires_at timestamptz DEFAULT (now() + '02:00:00'::interval)
);

CREATE TABLE public.shifts (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    library_id uuid REFERENCES public.libraries(id),
    code text NOT NULL CHECK (code = ANY (ARRAY['M'::text, 'A'::text, 'E'::text, 'N'::text])),
    name text NOT NULL,
    start_time time NOT NULL,
    end_time time NOT NULL
);

CREATE TABLE public.combo_plans (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    library_id uuid REFERENCES public.libraries(id),
    combination_key text NOT NULL,
    months integer NOT NULL CHECK (months >= 1 AND months <= 12),
    fee numeric NOT NULL
);

CREATE TABLE public.locker_policies (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    library_id uuid REFERENCES public.libraries(id) UNIQUE,
    eligible_combos text[] DEFAULT '{}'::text[],
    monthly_fee numeric NOT NULL,
    updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.seats (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    library_id uuid REFERENCES public.libraries(id),
    seat_number text NOT NULL,
    gender text NOT NULL CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'neutral'::text])),
    is_active boolean DEFAULT true
);

CREATE TABLE public.lockers (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    library_id uuid REFERENCES public.libraries(id),
    locker_number text NOT NULL,
    gender text NOT NULL CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'neutral'::text])),
    status text DEFAULT 'free'::text CHECK (status = ANY (ARRAY['free'::text, 'occupied'::text, 'key_pending'::text]))
);

CREATE TABLE public.students (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    library_id uuid REFERENCES public.libraries(id),
    name text NOT NULL,
    father_name text,
    address text,
    phone text CHECK (phone IS NULL OR phone ~ '^[6-9]\d{9}$'),
    gender text NOT NULL CHECK (gender = ANY (ARRAY['male'::text, 'female'::text])),
    seat_id uuid REFERENCES public.seats(id),
    combination_key text NOT NULL,
    shift_display text NOT NULL,
    selected_shifts text[] NOT NULL,
    locker_id uuid REFERENCES public.lockers(id),
    admission_date date DEFAULT CURRENT_DATE,
    plan_months integer NOT NULL CHECK (plan_months >= 1 AND plan_months <= 12),
    end_date date NOT NULL,
    payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['paid'::text, 'pending'::text, 'partial'::text, 'discounted'::text])),
    monthly_rate numeric NOT NULL,
    total_fee numeric NOT NULL,
    is_deleted boolean DEFAULT false,
    deleted_at timestamptz,
    created_at timestamptz DEFAULT now(),
    amount_paid numeric DEFAULT 0,
    discount_amount numeric DEFAULT 0
);

CREATE TABLE public.student_seat_shifts (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    student_id uuid REFERENCES public.students(id),
    seat_id uuid REFERENCES public.seats(id),
    shift_code text NOT NULL CHECK (shift_code = ANY (ARRAY['M'::text, 'A'::text, 'E'::text, 'N'::text])),
    end_date date NOT NULL
);

CREATE TABLE public.staff (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    library_ids uuid[] NOT NULL,
    user_id uuid REFERENCES auth.users(id) UNIQUE,
    name text NOT NULL,
    email text UNIQUE NOT NULL,
    role text DEFAULT 'staff'::text CHECK (role = ANY (ARRAY['owner'::text, 'staff'::text])),
    staff_type text DEFAULT 'specific'::text CHECK (staff_type = ANY (ARRAY['specific'::text, 'combined'::text])),
    is_active boolean DEFAULT true,
    force_password_change boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE public.payment_records (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    library_id uuid REFERENCES public.libraries(id),
    student_id uuid REFERENCES public.students(id),
    amount numeric NOT NULL,
    payment_method text DEFAULT 'cash'::text CHECK (payment_method = ANY (ARRAY['cash'::text, 'upi'::text, 'online'::text, 'other'::text])),
    payment_date date DEFAULT CURRENT_DATE,
    received_by uuid REFERENCES auth.users(id),
    notes text,
    type text NOT NULL CHECK (type = ANY (ARRAY['admission'::text, 'renewal'::text, 'locker_deposit'::text])),
    created_at timestamptz DEFAULT now()
);

CREATE TABLE public.subscription_payments (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    library_id uuid REFERENCES public.libraries(id),
    razorpay_order_id text UNIQUE NOT NULL,
    razorpay_payment_id text,
    razorpay_signature text,
    amount numeric NOT NULL,
    plan text NOT NULL,
    status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text])),
    processed boolean DEFAULT false,
    type text NOT NULL CHECK (type = ANY (ARRAY['registration'::text, 'renewal'::text])),
    created_at timestamptz DEFAULT now()
);

CREATE TABLE public.pricing_config (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    plan text UNIQUE NOT NULL CHECK (plan = ANY (ARRAY['1m'::text, '3m'::text, '6m'::text, '12m'::text])),
    amount numeric NOT NULL,
    updated_at timestamptz DEFAULT now(),
    duration_minutes integer DEFAULT 43200
);

CREATE TABLE public.notifications (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    library_id uuid REFERENCES public.libraries(id),
    type text NOT NULL CHECK (type = ANY (ARRAY['expiry_warning'::text, 'subscription_expiry'::text, 'new_admission'::text, 'fee_collected'::text, 'renewal_done'::text, 'student_renewed'::text, 'seat_changed'::text, 'data_cleanup_warning'::text])),
    title text NOT NULL,
    message text NOT NULL,
    student_id uuid REFERENCES public.students(id),
    is_read boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE public.contact_messages (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name text NOT NULL,
    phone text NOT NULL CHECK (phone ~ '^[6-9]\d{9}$'),
    message text NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE public.financial_events (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    library_id uuid REFERENCES public.libraries(id),
    student_id uuid REFERENCES public.students(id),
    student_name text NOT NULL,
    event_type text NOT NULL CHECK (event_type = ANY (ARRAY['ADMISSION_FULL'::text, 'ADMISSION_PARTIAL'::text, 'ADMISSION_PENDING'::text, 'PAYMENT_RECEIVED'::text, 'DISCOUNT_APPLIED'::text, 'RENEWAL'::text, 'REFUND_ON_DELETE'::text, 'NO_REFUND_ON_DELETE'::text])),
    amount numeric DEFAULT 0,
    pending_amount numeric DEFAULT 0,
    payment_mode text DEFAULT 'cash'::text,
    actor_role text NOT NULL CHECK (actor_role = ANY (ARRAY['owner'::text, 'staff'::text])),
    actor_name text NOT NULL,
    note text,
    created_at timestamptz DEFAULT now()
);

-- Row Level Security

ALTER TABLE public.libraries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.temp_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.combo_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locker_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lockers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_seat_shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscription_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_events ENABLE ROW LEVEL SECURITY;

-- Policies

-- libraries
CREATE POLICY libraries_select ON public.libraries FOR SELECT TO authenticated USING (id = ANY (get_user_library_ids()));
CREATE POLICY libraries_insert ON public.libraries FOR INSERT TO authenticated WITH CHECK (owner_id = auth.uid());
CREATE POLICY libraries_update ON public.libraries FOR UPDATE TO authenticated USING (owner_id = auth.uid());
CREATE POLICY libraries_delete ON public.libraries FOR DELETE TO authenticated USING (owner_id = auth.uid());

-- students
CREATE POLICY students_select ON public.students FOR SELECT TO authenticated USING (library_id = ANY (get_user_library_ids()));
CREATE POLICY students_insert ON public.students FOR INSERT TO authenticated WITH CHECK (library_id = ANY (get_user_library_ids()));
CREATE POLICY students_update ON public.students FOR UPDATE TO authenticated USING (library_id = ANY (get_user_library_ids()));
CREATE POLICY students_delete ON public.students FOR DELETE TO authenticated USING (is_library_owner(library_id));

-- seats
CREATE POLICY seats_select ON public.seats FOR SELECT TO authenticated USING (library_id = ANY (get_user_library_ids()));
CREATE POLICY seats_modify ON public.seats FOR ALL TO authenticated USING (is_library_owner(library_id));

-- lockers
CREATE POLICY lockers_select ON public.lockers FOR SELECT TO authenticated USING (library_id = ANY (get_user_library_ids()));
CREATE POLICY lockers_modify ON public.lockers FOR ALL TO authenticated USING (is_library_owner(library_id));

-- shifts
CREATE POLICY shifts_select ON public.shifts FOR SELECT TO authenticated USING (library_id = ANY (get_user_library_ids()));
CREATE POLICY shifts_modify ON public.shifts FOR ALL TO authenticated USING (is_library_owner(library_id));

-- combo_plans
CREATE POLICY combo_plans_select ON public.combo_plans FOR SELECT TO authenticated USING (library_id = ANY (get_user_library_ids()));
CREATE POLICY combo_plans_modify ON public.combo_plans FOR ALL TO authenticated USING (is_library_owner(library_id));

-- locker_policies
CREATE POLICY locker_policies_select ON public.locker_policies FOR SELECT TO authenticated USING (library_id = ANY (get_user_library_ids()));
CREATE POLICY locker_policies_modify ON public.locker_policies FOR ALL TO authenticated USING (is_library_owner(library_id));

-- staff
CREATE POLICY staff_select ON public.staff FOR SELECT TO authenticated USING (library_ids && get_user_library_ids());

-- notifications
CREATE POLICY notifications_select ON public.notifications FOR SELECT TO authenticated USING (library_id = ANY (get_user_library_ids()));
CREATE POLICY notifications_update ON public.notifications FOR UPDATE TO authenticated USING (library_id = ANY (get_user_library_ids()));
CREATE POLICY "staff can insert notifications" ON public.notifications FOR INSERT TO public WITH CHECK (library_id IN ( SELECT unnest(staff.library_ids) AS unnest FROM staff WHERE (staff.user_id = auth.uid())));

-- payment_records
CREATE POLICY payment_records_select ON public.payment_records FOR SELECT TO authenticated USING (library_id = ANY (get_user_library_ids()));
CREATE POLICY payment_records_insert ON public.payment_records FOR INSERT TO authenticated WITH CHECK (library_id = ANY (get_user_library_ids()));

-- pricing_config
CREATE POLICY pricing_config_select ON public.pricing_config FOR SELECT TO authenticated USING (true);

-- contact_messages
CREATE POLICY contact_messages_insert ON public.contact_messages FOR INSERT TO anon, authenticated WITH CHECK (true);

-- student_seat_shifts
CREATE POLICY "staff can insert seat shifts" ON public.student_seat_shifts FOR INSERT TO public WITH CHECK (seat_id IN ( SELECT seats.id FROM seats WHERE (seats.library_id IN ( SELECT unnest(staff.library_ids) AS unnest FROM staff WHERE (staff.user_id = auth.uid())))));
CREATE POLICY "staff can select seat shifts" ON public.student_seat_shifts FOR SELECT TO public USING (seat_id IN ( SELECT seats.id FROM seats WHERE (seats.library_id IN ( SELECT unnest(staff.library_ids) AS unnest FROM staff WHERE (staff.user_id = auth.uid())))));
CREATE POLICY "staff can delete seat shifts" ON public.student_seat_shifts FOR DELETE TO public USING (seat_id IN ( SELECT seats.id FROM seats WHERE (seats.library_id IN ( SELECT unnest(staff.library_ids) AS unnest FROM staff WHERE (staff.user_id = auth.uid())))));

-- financial_events
CREATE POLICY "staff can insert financial events" ON public.financial_events FOR INSERT TO public WITH CHECK (library_id IN ( SELECT unnest(staff.library_ids) AS unnest FROM staff WHERE (staff.user_id = auth.uid())));
CREATE POLICY "staff can select financial events" ON public.financial_events FOR SELECT TO public USING (library_id IN ( SELECT unnest(staff.library_ids) AS unnest FROM staff WHERE (staff.user_id = auth.uid())));
